### ISSUE TITLE
HdyViewSwitcher and HdyViewSwitcherBar ugly

### ISSUE THREAD

**Issue by ToxicDragon** [nilanshu96/Simple-Organizer#1]
Hi @nilanshu96 
Thank you for your great example of libhandy!

However, as I can see in your gif and also experience when building locally (the correspondig python version), the HdyViewSwitcher and HdyViewSwitcherBar look quite "ugly" compared to the preview in Builder/Glade and the pictures shown in https://tuxphones.com/tutorial-developing-responsive-linux-smartphone-apps-gnome-builder-gtk-libhandy-gtk-part-1/.

Here is the example picture of how it compares on my local machine:
![image](https://user-images.githubusercontent.com/3375142/99134724-48abea80-261f-11eb-9d54-1ba112f901e4.png)

Do you know how to get the correct styles for HdyViewSwitcher and HdyViewSwitcherBar?

Thanks in advance!

Christian

**Comment by nilanshu96** [comment]
Hi Christian, 

Yes you're right about it being ugly. I've made the policy for HdyViewSwithcer to be narrow permanently. It is much better now but not the best. I'm guessing it can be made even better using css but I'm not sure. Anyway can you please pull my new changes and see how it looks?

**Comment by nilanshu96** [comment]
One more thing, the looks also depend on the system theme. The one in the tutorial definitely has a different system theme. You can experiment with css or trying different system themes. I'll also try and see but it's better to have it depend on the system theme to keep a uniform look.

**Comment by ToxicDragon** [comment]
Hi @nilanshu96 
Thank you for your quick reply! I actually also raised a bug in libhandy repository directly :) https://gitlab.gnome.org/GNOME/libhandy/-/issues/367#note_960898
It turns out that in the new version of libhandy, one is to call `Handy.init()` (which is not done in the tutorial either...). After doing so, at least the Python version works consistently in terms of visuals to the output of Builder (see the attached graphic). I hope there is a way you can also apply this in your C version?

![image](https://user-images.githubusercontent.com/3375142/99144695-4b7efd80-2668-11eb-86cc-e285bef6d78d.png)

**Comment by nilanshu96** [comment]
Thank you so much! I did do hdy_init() in C because without that it simple doesn't work. Anyway thanks for informing me. I'll try to find some solution.

**Comment by nilanshu96** [comment]
I've raised an issue https://gitlab.gnome.org/GNOME/libhandy/-/issues/368 because I didn't find any solution on my own. Hopefully I do find some answer.

**Comment by nilanshu96** [comment]
It's a system theme issue in my case because of PopOS. Closing the issue. Should work in systems with vanilla Gnome theme.
